### ISSUE TITLE
the result of 'parseInt(cast[string](n.t[]), result, start)' not equal  L

### ISSUE THREAD

**Issue by cn-care** [Araq/packedjson#1]
When using the getInt() method, I often encounter the following problems, even if the value I'm passing is an int.

/root/.nimble/pkgs/packedjson-0.1.0/packedjson.nim(565, 12) `parseInt(cast[string](n.t[]), result, start) == L`

**Comment by Araq** [comment]
How to reproduce?

**Comment by cn-care** [comment]
```nim
import packedjson
var msg = %*{
    "itemId":25,
    "cityId":15
}
var itemId = msg["itemId"].getInt
var cityId = msg["cityId"].getInt
```
