### ISSUE TITLE
Cannot import packedjson

### ISSUE THREAD

**Issue by zendbit** [Araq/packedjson#7]
Hi, I am newbie want to use packedjson from the nimble directory.

Downloading https://github.com/Araq/packedjson using git
  Verifying dependencies for packedjson@0.1.0
 Installing packedjson@0.1.0
    Prompt: packedjson@0.1.0 already exists. Overwrite? [y/N]
    Answer:    Success: packedjson installed successfully.

but when I import on the .nim file, there is error said that cannot open packedjson
import packedjson <- error cannot open file packedjson

what I am missing to use and make packed json work?

Thanks,

**Comment by Araq** [comment]
Seems to be a problem with your Nimble installation.

**Comment by zendbit** [comment]
But I try to install other package working as expected.
I will figure it out later anyway..
Thanks for the hints :-)

When I try to view the pkgs directory in the packaedjson there is no packedjson.nim.

amru@Amru-Macbook-Air ~ % ls .nimble/pkgs/packedjson-0.1.0 
nimblemeta.json		packedjson.nimble
amru@Amru-Macbook-Air ~ % ls .nimble/pkgs/jester-0.4.3               
jester		jester.nim	jester.nimble	nimblemeta.json
amru@Amru-Macbook-Air ~ %

**Comment by rominf** [comment]
I have the same problem. I have nim 1.2.0 installed using choosenim. My OS is Fedora 31.

**Comment by SolitudeSF** [comment]
how are you invoking the compiler? when are you seeing the error?

**Comment by planetis-m** [comment]
Its a nimble issue. 
``nimble install packedjson`` does not install ``packedjson.nim``.
my ``~/.nimble/pkgs/packedjson-0.xx`` only contains ``nimblemeta.json`` and ``packedjson.nimble``

**Comment by Araq** [comment]
But maybe it's because Nimble wants it to be in ``src/packedjson`` or similar.
